version: "3.5"
services:
  web:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 80
    volumes:
      - ./app:/code/app  # Monta o código local para hot-reload
    env_file:
      - .env
    ports:
      - "5050:80"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@db:5432/fastapi_db}
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-fastapi_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "2345:5432"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
